### ISSUE TITLE
NoSuchFileException

### ISSUE THREAD

**Issue by flobizDipen** [zetbaitsu/Compressor#159]
Fatal Exception: kotlin.io.NoSuchFileException: : The source file doesn't exist.
       at kotlin.io.FilesKt__UtilsKt.copyTo(FilesKt__UtilsKt.java:183)
       at kotlin.io.FilesKt__UtilsKt.copyTo$default(FilesKt__UtilsKt.java:181)
       at id.zelory.compressor.UtilKt.copyToCache(UtilKt.java:82)
       at id.zelory.compressor.Compressor$compress$3.invokeSuspend(Compressor.java:25)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:241)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$createdWorkers(CoroutineScheduler.java:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:740)

**Comment by nareshkatta99** [comment]
This could be due to read permissions.
If you already added read permissions, there could be some issues due to Nougat version.In that case try adding
```
android:requestLegacyExternalStorage="true"
```
to application tag in manifest.

**Comment by Pradeep0801** [comment]
Fatal Exception: 
kotlin.io.NoSuchFileException: /storage/emulated/0/Android/media/YYYs/XXXX/2020-10-13-13-29-22-623.jpg: The source file doesn't exist.
       at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:183)
       at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:181)
       at id.zelory.compressor.UtilKt.copyToCache(Util.kt:82)
       at id.zelory.compressor.Compressor$compress$3.invokeSuspend(Compressor.kt:25)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

**Comment by Pradeep0801** [comment]
android:requestLegacyExternalStorage="true" this is already added in manifest

**Comment by Pradeep0801** [comment]
this issues is happening in 3.0.0 before this version app is working fine

**Comment by Protino** [comment]
@Pradeep0801 Is it happening on MI devices by any chance. Have been receiving reports on this device.

**Comment by Protino** [comment]
> this issues is happening in 3.0.0 before this version app is working fine

Happening on 2.x too.

**Comment by amrro** [comment]
You can found util functions to solve this issue: [FileUtil.java](https://github.com/zetbaitsu/Compressor/blob/master/app/src/main/java/id/zelory/compressor/sample/FileUtil.java)

You can found more [here](https://stackoverflow.com/a/59123287/2489403).

**Comment by NailPlay** [comment]
Decision?

**Comment by pradeep-orbi** [comment]
What is the fix for this issue ?

**Comment by bymomo** [comment]
Solved, copy the code from this file and use the methods inside to convert the URI to file.
https://github.com/zetbaitsu/Compressor/blob/master/app/src/main/java/id/zelory/compressor/sample/FileUtil.java
