### ISSUE TITLE
BitmapFactory.decodeFile(absolutePath, this) must not be null

### ISSUE THREAD

**Issue by aliahsan-ch** [zetbaitsu/Compressor#168]
Implementation:
```
lifecycleScope.launch {
                 val compressedPhotoPath = Compressor.compress(requireContext(),originalPhotoFile)
                }
```

Exception:

```
Fatal Exception: java.lang.IllegalStateException: BitmapFactory.decodeFile…eFile.absolutePath, this) must not be null
       at id.zelory.compressor.UtilKt.decodeSampledBitmapFromFile(Util.kt:45)
       at id.zelory.compressor.constraint.DefaultConstraint.satisfy(DefaultConstraint.kt:28)
       at id.zelory.compressor.Compressor$compress$3.invokeSuspend(Compressor.kt:28)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by r4phab** [comment]
Same issue on multiple Xiaomi devices and a P30 Pro for now .... 👎🏻 

Is there anything we can do to prevent this crash ?

**Comment by aliahsan-ch** [comment]
@r4phab Currently, as a workaround, we have created an extension to fall back to the uncompressed file in case of an exception but this should be fixed.

**Comment by XuQK** [comment]
How do yout catch this exception? I tried some methods, but failed. help me please.

**Comment by adesamp** [comment]
is this issue has fix version ?

**Comment by khanjaved975** [comment]
is it fixed version  now?

**Comment by MahmoudMabrok** [comment]
still issue occurs.

**Comment by pradeep-orbi** [comment]
Still facing this issue.

**Comment by mochadwi** [comment]
This might be happened, if we try to create a temporary file (not an image type). 

In our case:
1. we make sure when creating temporary files (before take picture/open camera)
2. 1do nothing for the files (no compression)
3. afterward `onActivityResult` called, the `Uri` now used either to update the previous temporary files or try to compress the `Uri` (convert it to a `File` first)

This is also sometimes related to Android 10 & above permission, when trying to open/retrieve files from `/Android/data`, as mentioned in here: https://developer.android.com/about/versions/11/privacy/storage#file-access

**Comment by BraveEvidence** [comment]
Any updates on this?

**Comment by eric-ampire** [comment]
Still have the issue

**Comment by kevinmf1** [comment]
For those facing similar issues, I created a lightweight Android image compression library called ImageSqueeze.

It follows a similar idea to Compressor but with a simpler API.

Repo: https://github.com/kevinmf1/ImageSqueeze
