### ISSUE TITLE
Fatal Exception: IllegalStateException

### ISSUE THREAD

**Issue by utsavDave97** [zetbaitsu/Compressor#177]
`Fatal Exception: java.lang.IllegalStateException: this must not be null
       at id.zelory.compressor.UtilKt.loadBitmap(Util.kt:34)
       at id.zelory.compressor.constraint.QualityConstraint.satisfy(QualityConstraint.kt:21)
       at id.zelory.compressor.Compressor$compress$3.invokeSuspend(Compressor.kt:28)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
`

any idea why?

**Comment by prudhvir3ddy** [comment]
@utsavDave97 got any update for this ?

**Comment by utsavDave97** [comment]
@prudhvir3ddy no update yet. Sorry. You getting the same exception?

**Comment by prudhvir3ddy** [comment]
Yes

**Comment by nareshkatta99** [comment]
Are you getting this error on all devices or specific to single device?

**Comment by SilvestreRamirez** [comment]
i have the same exception, got any update for this ?

**Comment by utsavDave97** [comment]
No update. But most likely will change the library. @nareshkatta99  @prudhvir3ddy @SilvestreRamirez

**Comment by nareshkatta99** [comment]
It wold be very helpful for us if you provide minimal code to reproduce this error.
Will try to resolve ASAP.
@utsavDave97 @prudhvir3ddy @SilvestreRamirez

**Comment by utsavDave97** [comment]
Devices in which this is seen most are Galaxy A50,A51 , moto g-fast, Galaxy S20 5G

**Comment by Sabboo** [comment]
I am facing the same issue with _**Samsung Galaxy S8**_ running _**OS 9**_
But before this exception I am getting this error 
`skia -- Failed to create image decoder with message 'unimplemented'`

**Comment by Sabboo** [comment]
I am facing the same issue with Samsung Galaxy S8 running OS 9

**Comment by paragRaneWork** [comment]
I am facing the same issue with Samsung Galaxy M31s

**Comment by ly469097645** [comment]
Same issue on Redmi 9A devices

Is there anything we can do to prevent this crash ?

**Comment by krunalpatel3** [comment]
if you trying to compress .tiff image or any unsupported format that Compressor Library do not support that this occurs.
put validation before you start to Compress image.

**Comment by kevinmf1** [comment]
For those facing similar issues, I created a lightweight Android image compression library called ImageSqueeze.

It follows a similar idea to Compressor but with a simpler API.

Repo: https://github.com/kevinmf1/ImageSqueeze
