### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: UtilKt.decodeSampledBitmapFromFile

### ISSUE THREAD

**Issue by joelkanyi** [zetbaitsu/Compressor#217]
```
Fatal Exception: java.lang.IllegalStateException: BitmapFactory.decodeFile…eFile.absolutePath, this) must not be null
       at id.zelory.compressor.UtilKt.decodeSampledBitmapFromFile(Util.kt:45)
       at id.zelory.compressor.constraint.DefaultConstraint.satisfy(DefaultConstraint.kt:28)
       at id.zelory.compressor.Compressor$compress$3.invokeSuspend(Compressor.kt:28)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:585)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
        
```

**Comment by panky1** [comment]
Same issue facing on my side as well any update on this fixes

**Comment by panky1** [comment]
id.zelory.compressor.UtilKt.decodeSampledBitmapFromFile (Util.kt:45)
id.zelory.compressor.constraint.DefaultConstraint.satisfy (DefaultConstraint.kt:28)
id.zelory.compressor.Compressor$compress$3.invokeSuspend (Compressor.kt:28)
id.zelory.compressor.Compressor$compress$3.invoke (Compressor.kt:10)
kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn (Undispatched.kt:78)
kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext (Builders.common.kt:167)
kotlinx.coroutines.BuildersKt.withContext (Builders.kt)
id.zelory.compressor.Compressor.compress (Compressor.kt:23)
id.zelory.compressor.Compressor.compress$default (Compressor.kt:22)
app.CompressImage.compressFile (CompressImage.kt:13)
app.CompressImage$compressFileFromJava$1.invokeSuspend (CompressImage.kt:19)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:108)
kotlinx.coroutines.internal.LimitedDispatcher$Worker.run (LimitedDispatcher.kt:115)
kotlinx.coroutines.scheduling.TaskImpl.run (Tasks.kt:103)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:584)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:793)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:697)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt)

**Comment by kevinmf1** [comment]
If anyone is looking for a modern alternative, I recently built a small image compression library for Android called ImageSqueeze.

It’s inspired by Compressor but written with a more modern approach.

https://github.com/kevinmf1/ImageSqueeze
