### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by yliang11** [zetbaitsu/Compressor#49]
When I choose some pictures，it may happen，how can i fix it？

  at id.zelory.compressor.ImageUtil.getScaledBitmap(ImageUtil.java:62)
     actualWidth = bitmap2.getWidth();

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

**Comment by yuhaodev** [comment]
I meet the same problem,as well

**Comment by IgorHorta** [comment]
updates on this ?

**Comment by yliang11** [comment]
@IgorHorta  it's not the problem of permission, not every picture can happen，some picture will happen,but some not.I dont know why

**Comment by Mistic92** [comment]
I have the same problem. For some pictures it's working but for some I get error.

**Comment by lilealyh** [comment]
@IgorHorta I also have the same problem.When called setDestinationDirectoryPath() method, I set to my source file path as a result path that is setDestinationDirectoryPath(sourceFilePath) ,so I meet this error.

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference 
at id.zelory.compressor.ImageUtil.decodeSampledBitmapFromFile(ImageUtil.java:70)
at id.zelory.compressor.ImageUtil.compressImage(ImageUtil.java:33) 
at id.zelory.compressor.Compressor.compressToFile(Compressor.java:60) 
at id.zelory.compressor.Compressor.compressToFile(Compressor.java:56)

**Comment by hkk565** [comment]
This happens when you set the destination directory same as that of the original image file. A work-around is to set a different directory for the compressed image.

**Comment by zkjmyy** [comment]
How dou you fix?

**Comment by lilealyh** [comment]
@hkk565  I want set the same destination directory so that to cover the old image.How to fix this bug?Thanks

**Comment by hkk595** [comment]
@lilealyh I don't recommend you overwriting the original image directly. Because if the compression process somehow fails in the middle, the original image will be destroyed as well. If you have to do this, a work-around is to generate the compressed image file at a different temporary directory first (such as the external cache directory). When it's done, delete the original image file and move the compressed image file to the original directory (using Android I/O APIs).

**Comment by 18705320883** [comment]
the reason is that you save your compressed file in the same folder and name with original image,
just use compressToFile(File imageFile, String compressedFileName) to use a different name with de original image.

**Comment by gelbertgel** [comment]
I have same issue. Please help me.

    ```
private File compressImageAnotherLibrary(int width, int height, int quality, File file) {

        try {
            return new Compressor(mContext)
                    .setQuality(quality)
                    .setMaxWidth(width)
                    .setDestinationDirectoryPath(new FileOperations().createMediaFile(Message.messageType.image.toString(), imageExtension, false).getAbsolutePath())
                    .setMaxHeight(height)
                    .setCompressFormat(Bitmap.CompressFormat.JPEG)
                    .compressToFile(file);

        } catch (IOException e) {
            Mylog.printStackTrace(TAG + "compressImageAnotherLibrary error ", e);

            return null;
        }
    }
```

**Comment by tellfa** [comment]
I have this error! how can i fix it?

**Comment by mpardalm** [comment]
How con I fix this error? I don't know how to continue with the compressor


java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                               at id.zelory.compressor.ImageUtil.decodeSampledBitmapFromFile(ImageUtil.java:70)
                                                                               at id.zelory.compressor.ImageUtil.compressImage(ImageUtil.java:33)
                                                                               at id.zelory.compressor.Compressor.compressToFile(Compressor.java:60)
                                                                               at id.zelory.compressor.Compressor.compressToFile(Compressor.java:56)

Thank you!

**Comment by vikasgupta4190** [comment]
if (actualImage == null) {
            showError("Please choose an image!");
        } else {

            BitmapFactory.Options options = new BitmapFactory.Options();
            options.inPreferredConfig = Bitmap.Config.ARGB_8888;
            Bitmap bitmap =
BitmapFactory.decodeFile(actualImage.getAbsolutePath(), options);

            if(!(bitmap.getWidth() == 0 && bitmap.getHeight() == 0)) {
                // Compress image in main thread using custom Compressor
                compressedImage = new Compressor.Builder(this)
                        .setMaxWidth(1376)
                        .setMaxHeight(756)
                        .setQuality(90)
                        .setCompressFormat(Bitmap.CompressFormat.JPEG)

.setDestinationDirectoryPath(Environment.getExternalStoragePublicDirectory(

Environment.DIRECTORY_PICTURES+"/engcomm").getAbsolutePath())
                        .build()
                        .compressToFile(actualImage);
                setCompressedImage();

            }

**Comment by vikasgupta4190** [comment]
if (actualImage == null) {
showError("Please choose an image!");
} else {

BitmapFactory.Options options = new BitmapFactory.Options();
options.inPreferredConfig = Bitmap.Config.ARGB_8888;
Bitmap bitmap = BitmapFactory.decodeFile(actualImage.getAbsolutePath(),
options);

if(!(bitmap.getWidth() == 0 && bitmap.getHeight() == 0)) {
// Compress image in main thread using custom Compressor
compressedImage = new Compressor.Builder(this)
.setMaxWidth(1376)
.setMaxHeight(756)
.setQuality(90)
.setCompressFormat(Bitmap.CompressFormat.JPEG)
.setDestinationDirectoryPath(Environment.getExternalStoragePublicDirectory(
Environment.DIRECTORY_PICTURES+"/engcomm").getAbsolutePath())
.build()
.compressToFile(actualImage);
setCompressedImage();

}

**Comment by vikasgupta4190** [comment]
if (actualImage == null) {
showError("Please choose an image!");
} else {

BitmapFactory.Options options = new BitmapFactory.Options();
options.inPreferredConfig = Bitmap.Config.ARGB_8888;
Bitmap bitmap = BitmapFactory.decodeFile(actualImage.getAbsolutePath(),
options);

if(!(bitmap.getWidth() == 0 && bitmap.getHeight() == 0)) {
// Compress image in main thread using custom Compressor
compressedImage = new Compressor.Builder(this)
.setMaxWidth(1376)
.setMaxHeight(756)
.setQuality(90)
.setCompressFormat(Bitmap.CompressFormat.JPEG)
.setDestinationDirectoryPath(Environment.getExternalStoragePublicDirectory(
Environment.DIRECTORY_PICTURES+"/engcomm").getAbsolutePath())
.build()
.compressToFile(actualImage);
setCompressedImage();

}

**Comment by mbosecke** [comment]
If it helps anyone else, I get the error when I try to compress an empty file. My solution was to check the file size before invoking the compression library (and also investigate why I my app has empty files in the first place):

    if(photoFile != null && photoFile.length() > 0){
        File compressed = new Compressor(this).compressToFile(photoFile);
    }

**Comment by jlubeck** [comment]
Using the same directory between original and compressed was my cause of this error. Would be nice to see a proper error instead of this one that doesn't really help.

Thank you for the people that mentioned that option!

**Comment by cdreamplayer** [comment]
Choiced the output image to compress was my cause of this error.
I resolve this problem with delete the output image after using it.

**Comment by Sainathhiwale** [comment]
Hi Guys 
add image temp file storage it's working fine 


 private void openCamera() throws IOException {
        Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        photoFile = createImageFile();
        photoURI = FileProvider.getUriForFile(getActivity(), getActivity().getPackageName() + ".provider", photoFile);
        intent.putExtra(MediaStore.EXTRA_OUTPUT, FileProvider.getUriForFile(getActivity(), getActivity().getPackageName() + ".provider", photoFile));
        startActivityForResult(intent, IMAGE_CAPTURE_CODE);
    }
private File createImageFile() throws IOException {
        // Create an image file name
        File storageDir = getActivity().getExternalFilesDir(Environment.DIRECTORY_PICTURES);
        image = File.createTempFile(
                "temp",  /* prefix */
                ".jpg",         /* suffix */
                storageDir      /* directory */
        );
//        Log.e(TAG, "createImageFile: "+image.getAbsolutePath() );
        mImageFileLocation = image.getAbsolutePath();
        if (image.exists()) {
            image.delete();
        }
        return image;
    }

 BitmapFactory.Options bmOptions = new BitmapFactory.Options();
            bmOptions.inJustDecodeBounds = true;
            BitmapFactory.decodeFile(mImageFileLocation, bmOptions);
            int cameraImageWidth = bmOptions.outWidth;
            int cameraImageHeight = bmOptions.outHeight;

            int scaleFactor = Math.min(cameraImageWidth / targetImageViewWidth, cameraImageHeight / targetImageViewHeight);
            bmOptions.inSampleSize = scaleFactor;
            bmOptions.inJustDecodeBounds = false;
            Bitmap photoReducedSizeBitmp = BitmapFactory.decodeFile(mImageFileLocation, bmOptions);

           /* BitmapFactory.Options options = new BitmapFactory.Options();
            options.inPreferredConfig = Bitmap.Config.ARGB_8888;
            Bitmap photoReducedSizeBitmp = BitmapFactory.decodeFile(mImageFileLocation, options);
*/

            try {
                compressedImageFile = new Compressor(Objects.requireNonNull(getActivity())).compressToFile(new File(mImageFileLocation));

            } catch (IOException e) {
                e.printStackTrace();
            }

**Comment by javakam** [comment]
我的方式
```
    compileOnly "androidx.exifinterface:exifinterface:1.3.2"
    replace `android.media.ExifInterface` with `androidx.exifinterface.media.ExifInterface`
```

**Comment by kevinmf1** [comment]
For those facing similar issues, I created a lightweight Android image compression library called ImageSqueeze.

It follows a similar idea to Compressor but with a simpler API.

Repo: https://github.com/kevinmf1/ImageSqueeze
