### ISSUE TITLE
java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by umesh0492** [zetbaitsu/Compressor#56]
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:967)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
    at id.zelory.compressor.ImageUtil.getScaledBitmap(ImageUtil.java:116)
    at id.zelory.compressor.ImageUtil.compressImage(ImageUtil.java:161)
    at id.zelory.compressor.Compressor.compressToFile(Compressor.java:48)

receiving in 

DEVICE config

Android    6.01
Family	samsung
Model	on7xeltedd (SM-G610F)
Architecture	armv8l
Orientation	portrait
screen_resolution	1920x1080

**Comment by YuanWenHai** [comment]
Try to check your arguments?
I encountered the same problem, finally I found it is caused by the wrong argument I passed.

**Comment by zetbaitsu** [comment]
try the latest version
