### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by ght199266** [zetbaitsu/Compressor#70]
FATAL EXCEPTION: main  java.lang.OutOfMemoryError
                                                                  at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:650)
                                                                  at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:389)
                                                                  at id.zelory.compressor.ImageUtil.decodeSampledBitmapFromFile(ImageUtil.java:49)
                                                                  at id.zelory.compressor.ImageUtil.compressImage(ImageUtil.java:27)
                                                                  at id.zelory.compressor.Compressor.compressToFile(Compressor.java:60)
                                                                  at id.zelory.compressor.Compressor.compressToFile(Compressor.java:56)
                                                                  at com.lly.testdemo.ImageCompressor$1.onClick(ImageCompressor.java:61)
                                                                  at android.view.View.performClick(View.java:4211)
                                                                  at android.view.View$PerformClick.run(View.java:17267)
                                                                  at android.os.Handler.handleCallback(Handler.java:615)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:4898)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:511)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by ght199266** [comment]
Samsung Gt-19300 
android 4.1.2

**Comment by IsaiasSantana** [comment]
@ght199266  This can happen. Bitmaps can very easily exhaust an app's memory budget. Maybe  to fix this, could use the glid library to load the images. Avoiding manage memory and disk caching.

**Comment by zhaozeyx** [comment]
![image](https://user-images.githubusercontent.com/4213414/37440415-927862ee-2837-11e8-86e7-f7ac7f47c22f.png)

Is it a problem? the bitmap decoded is not recycled, and I have no idea how to recycle the bitmap

**Comment by Duna** [comment]
Bitmap .Recycle()
