### ISSUE TITLE
Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference

### ISSUE THREAD

**Issue by sebamena** [zetbaitsu/Compressor#75]
Non-fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1269)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1325)
       at id.zelory.compressor.ImageUtil.getScaledBitmap(ImageUtil.java:129)
       at id.zelory.compressor.ImageUtil.compressImage(ImageUtil.java:161)
       at id.zelory.compressor.Compressor.compressToFile(Compressor.java:48)
       at com.example.luis.myapplication.Infofoto.onActivityResult(Infofoto.java:286)
       at android.app.Activity.dispatchActivityResult(Activity.java:6442)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by Laravel-storage** [comment]
This could enhance your understanding, https://overlay-progressive.github.io/I9HpQ6yPlrZoVVhYd_gLXMvVYmTzhY3jBPUPOn_DabafOhi6kW5-SJw/ I think
